### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by larymay** [frankmcsherry/COST#4]
Hello,

I am trying to run ./target/release/COST twitter twitter_rv_15066953.net small as written in the instructions and getting the following error message: 

thread '<main>' panicked at 'malformed dst', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:330

I am using RUST 1.0.0 64bit on Ubuntu 14.04.

Do you have any suggestions how I can fix this error?

Thank you in advance

Larissa

**Comment by frankmcsherry** [comment]
The error means that for some reason Rust didn't like the bit of text that was supplied to be parsed to an integer. This was previously a result of using `split` rather than `split_whitespace` in twitter_parser.rs, although that was fixed a while back.

I'm grabbing 1.0 now to try and reproduce, but in the meantime would you be willing to check that you have the most current twitter_parser.rs (with `split_whitespace` on line 46) and if so have Rust print out the line that it is mis-parsing?

**Comment by frankmcsherry** [comment]
It seems (for me) that 1.0 stable should not build if you have the most recent twitter_parser.rs. The `split_whitespace` method did not make it in to the 1.0 release, though I think it should be in beta and nightly now. If you are using beta or nightly and seeing the error with `split_whitespace` let me know!

**Comment by larymay** [comment]
Thank you for your quick reply. I tried it with beta and the error disappeared.

**Comment by frankmcsherry** [comment]
Hooray! :D
